services:
    # Main server
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 127.0.0.1:4080:4080
        depends_on:
            - db

    # Postgres Database
    db:
        image: "postgres:17"
        environment:
            POSTGRES_DB: db
            POSTGRES_USER: user
            POSTGRES_PASSWORD: pass
        ports:
            - 127.0.0.1:5432:5432
